// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('null values', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('null values', async function() {
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    await driver.manage().window().setRect({ width: 844, height: 720 })
    await driver.findElement(By.id("operator")).click()
    {
      const dropdown = await driver.findElement(By.id("operator"))
      await dropdown.findElement(By.xpath("//option[. = '+']")).click()
    }
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("5")
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.css("#num1:invalid"))
      assert(elements.length)
    }
  })
})
