// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addToCart_Cofirm', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addToCart_Cofirm', async function() {
    await driver.get("https://www.demoblaze.com/")
    vars["m"] = "Monitors"
    console.log(vars["m"])
    await driver.findElement(By.linkText("vars["m"]")).click()
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .card-img-top")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
    await driver.findElement(By.css(".active > .nav-link")).click()
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .card-img-top")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
    await driver.findElement(By.id("cartur")).click()
    vars["n"] = "talel"
    console.log(vars["n"])
    await driver.findElement(By.css(".btn-success")).click()
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.css("#orderModal #name"))), 30000)
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys(vars["n"])
    vars["c"] = "monastir"
    await driver.findElement(By.id("country")).sendKeys(vars["c"])
    vars["ci"] = "ksarhellal"
    await driver.findElement(By.id("city")).sendKeys(vars["ci"])
    await driver.findElement(By.id("card")).sendKeys("2154546464")
    await driver.findElement(By.id("month")).sendKeys("5")
    await driver.findElement(By.id("year")).sendKeys("2024")
    await driver.findElement(By.css("#orderModal .btn-primary")).click()
    assert(await driver.findElement(By.css(".sweet-alert h2")).getText() == "Thank you for your purchase!")
    await driver.findElement(By.css(".confirm")).click()
  })
})
