// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('other_pages', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('other_pages', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 1100, height: 816 })
    await driver.findElement(By.linkText("Contact")).click()
    await driver.findElement(By.id("recipient-email")).click()
    await driver.findElement(By.id("recipient-email")).sendKeys("talel@azokr.arjkl")
    await driver.findElement(By.id("recipient-name")).sendKeys("talel")
    await driver.findElement(By.id("message-text")).click()
    await driver.findElement(By.id("message-text")).sendKeys("fzefjkefeb")
    await driver.findElement(By.css("#exampleModal .btn-primary")).click()
    await driver.findElement(By.id("login2")).click()
    await driver.findElement(By.css("#logInModal .btn-secondary")).click()
    await driver.findElement(By.id("signin2")).click()
    await driver.findElement(By.css("#signInModal .btn-secondary")).click()
    await driver.findElement(By.linkText("About us")).click()
    await driver.findElement(By.css("#videoModal .btn")).click()
  })
})
