// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('parcourir_categories', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('parcourir_categories', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 836, height: 816 })
    await driver.findElement(By.id("itemc")).click()
    await driver.findElement(By.linkText("Laptops")).click()
    await driver.findElement(By.linkText("Monitors")).click()
  })
})
