// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test 1', async function() {
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/hello.html")
    await driver.manage().window().setRect({ width: 952, height: 1023 })
    vars["Username"] = "Heni"
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys(vars["Username"])
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Bonjour, vars[\"Username\"] !")
  })
})
